[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "aux8"
version = "0.1.0"

[dependencies]
cortex-m = "0.5.1"
cortex-m-rt = "0.5.1"

[dependencies.f3]
features = ["rt"]
version = "0.6.1"
